//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strix_Schedule
{
    using System;
    using System.Collections.Generic;

    public partial class Event
    {
        public int EventID { get; set; }
        public int EmployeeID { get; set; }
        public string Description { get; set; }
        public System.DateTime Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public bool IsFullDay { get; set; }
        public string ThemeColor { get; set; }

        public virtual Employee Employee { get; set; }
    }
}
